# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_cart_manager.class: Aisel\CartBundle\Manager\CartManager

services:
    aisel.cart.manager:
        class: %aisel_cart_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
