parameters:
    application.name: Aisel
    application.version: 0.1.0
    application.media.path: /media
    application.media.product.path: /media/product
    application.media.product.main.path: /media/product

aisel_config:
    settings_route: /%website_admin%/{_locale}/settings/{editLocale}
    route_prefix: config_ # ex: config_contact
    entities:
        homepage:
            order: 0
            controller: AiselSettingsBundle:ConfigHomepage:modify
        meta:
            order: 10
            controller: AiselSettingsBundle:ConfigMeta:modify
        disqus:
            order: 20
            controller: AiselSettingsBundle:ConfigDisqus:modify
        contact:
            order: 30
            controller: AiselContactBundle:Config:modify

aisel_fixture:
    xml_path: /fixtures/xml
