imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: twig.yml }
    - { resource: configs/doctrine.yml }
    - { resource: configs/aisel.yml }
    - { resource: configs/payum.yml }
    - { resource: configs/cors.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime: 0
        save_path: %kernel.root_dir%/var/sessions
        name: AISELSESSID
#        cookie_domain: .aisel.dev
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
    filters:
        cssrewrite: ~

# Annotations
sensio_framework_extra:
    view:
        annotations: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    spool:     { type: memory }

# JMS
jms_serializer:
  metadata:
    auto_detection: true

#
#services:
#    jms_serializer.doctrine_object_constructor:
#        class:        %jms_serializer.doctrine_object_constructor.class%
#        public:       false
#        arguments:    ["@doctrine_orm", "@jms_serializer.unserialize_object_constructor"]
#
#    jms_serializer.object_constructor:
#        alias: jms_serializer.doctrine_object_constructor
#        public: false

# REST
fos_rest:
    view:
        view_response_listener: 'force'