security:
    encoders:
        Aisel\FrontendUserBundle\Entity\FrontendUser: sha512
        Aisel\BackendUserBundle\Entity\BackendUser: sha512
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        user_frontend:
            entity: { class: AiselFrontendUserBundle:FrontendUser, property: username }
        user_backend:
            entity: { class: AiselBackendUserBundle:BackendUser, property: username }

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /%website_admin%/(.*)
            context:            admin
            form_login:
                provider:       user_backend
                login_path:     /%website_admin%/%locale%/login
                check_path:     /%website_admin%/%locale%/login_check
                default_target_path: /%website_admin%/%locale%/dashboard
                use_forward:    true
                failure_path:   null
            logout:
                path:           /%website_admin%/%locale%/logout
                target:         /%website_admin%/%locale%/
            anonymous:          false

        user:
            pattern:             .*
            context:             user
            form_login:
                login_path:     /%website_api%/user/information.json
            form_login:
                provider:       user_frontend
                use_forward:    true
                failure_path:   true
            anonymous:          true

    access_control:
        # Admin login needs to have access without any roles assigned
        - { path: ^/%website_admin%/%locale%/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%website_admin%/%locale%/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%website_admin%/%locale%/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/%website_admin%/%locale%/, role: [ROLE_ADMIN] }

        # Secured part of API
#        - { path: ^/%website_api%/orders.json, role: ROLE_USER }