---
  - name: Update apt
    sudo: yes
    apt:  update_cache=yes

  - name: Install system packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - curl
      - wget
      - build-essential
      - python-software-properties

  - name: Add ppa repository
    sudo: yes
    apt_repository: repo=ppa:ondrej/{{ php_ppa }}

  - name: Update apt again
    sudo: yes
    apt:  update_cache=yes

  - name: Install extra packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items: sys_packages
