admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /%website_admin%/{_locale}
    requirements:
      _locale: %locales%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /%website_admin%/{_locale}
    requirements:
      _locale: %locales%
