# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\OrderBundle\Entity\Order:
  exclusion_policy: ALL
  properties:
    id:
        expose: true
    status:
        expose: true
    status:
        expose: true
    subtotal:
        expose: true
    grandtotal:
        expose: true
    createdAt:
        expose: truetrue
    updatedAt:
        expose: true
    frontenduser:
        expose: false

    item:
        expose: true
