# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_contactsend:
    pattern:  /%frontend_api%/contact/message/
    defaults: { _controller: AiselContactBundle:Api:sendMessage, _format: json }
    requirements:
        _method: POST
