# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\AddressingBundle\Entity\Country:
  exclusion_policy: all
  properties:
    id:
        expose: true
    iso2:
        expose: true
    iso3:
        expose: true
    shortName:
        expose: true
    longName:
        expose: true
