# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\PageBundle\Entity\Page:
  exclusion_policy: all
  properties:
    id:
        expose: true
    title:
        expose: true
    content:
        expose: true
    createdAt:
        expose: true
    updatedAt:
        expose: true
    commentStatus:
        expose: true
    metaUrl:
        expose: true
    metaTitle:
        expose: true
    metaDescription:
        expose: true
    metaKeywords:
        expose: true
    status:
        expose: true
