# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

be_api_aisel_product:
    resource: "@AiselProductBundle/Resources/config/routing/backend.yml"
    prefix:   /%backend_api%

fe_api_aisel_product:
    resource: "@AiselProductBundle/Resources/config/routing/frontend.yml"
    prefix:   /%frontend_api%

seller_api_aisel_product:
    resource: "@AiselProductBundle/Resources/config/routing/seller.yml"
    prefix:   /%seller_api%
