# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    frontend.user.manager:
        class: Aisel\FrontendUserBundle\Manager\UserManager
        arguments:
          - @doctrine.orm.entity_manager
          - @security.encoder_factory
          - @security.context
          - @mailer
          - @templating
          - %website_email%
