# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_product_manager.class: Aisel\ProductBundle\Manager\ProductManager
    aisel_product_media_manager.class: Aisel\ProductBundle\Manager\MediaManager
    aisel_product_category_manager.class: Aisel\ProductBundle\Manager\ProductCategoryManager
    aisel_product_category_node_manager.class: Aisel\ProductBundle\Manager\NodeManager

services:
    aisel.product.manager:
        class: %aisel_product_manager.class%
        arguments: [@doctrine.orm.entity_manager]

    aisel.product.media.manager:
        class: %aisel_product_media_manager.class%
        arguments: [@doctrine.orm.entity_manager, %application.media.product.path%, %website_address%]

    aisel.productcategory.manager:
        class: %aisel_product_category_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]

    aisel.productcategory.node.manager:
        class: %aisel_product_category_node_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]

    sonata.admin.product:
        class: Aisel\ProductBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Catalog", label: "Products" }
        arguments:
            - ~
            - Aisel\ProductBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [forms]]
            - [ setManager, [@aisel.product.manager]]
            - [ setTemplate, [edit, AiselProductBundle:CRUD:edit.html.twig]]

    sonata.admin.product.category:
        class: Aisel\ProductBundle\Admin\ProductCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Catalog", label: "Categories" }
        arguments:
            - ~
            - Aisel\ProductBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [forms]]
            - [ setTemplate, [list, AiselProductBundle:Tree:list.html.twig]]
            - [ setManager, [@aisel.productcategory.manager]]
